"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { AlertCircle, ArrowLeft, ClipboardCopy, Play, RefreshCw } from "lucide-react";
import type { ReactNode } from "react";
import { useEffect, useState } from "react";

import { AppShell } from "@/components/layout/app-shell";
import { DefenseQuestionsList } from "@/components/report/defense-questions-list";
import { PriorityFixList } from "@/components/report/priority-fix-list";
import { OverallScoreCard, ScoreBreakdownCards } from "@/components/report/score-cards";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getReport, type Report } from "@/lib/api";
import { cn } from "@/lib/utils";

export default function FinalReportPage() {
  const params = useParams<{ projectId: string; reportId: string }>();
  const projectId = params.projectId;
  const reportId = params.reportId;
  const [report, setReport] = useState<Report | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isCopying, setIsCopying] = useState(false);
  const [copyState, setCopyState] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function loadReport() {
    setIsLoading(true);
    setError(null);
    setCopyState(null);

    try {
      const response = await getReport(reportId);
      if (response.project_id !== projectId) {
        throw new Error("This report does not belong to the selected project.");
      }
      setReport(response);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not load report.");
    } finally {
      setIsLoading(false);
    }
  }

  useEffect(() => {
    void loadReport();
  }, [projectId, reportId]);

  async function copyReport() {
    if (!report) {
      return;
    }

    setIsCopying(true);
    setCopyState(null);
    try {
      await navigator.clipboard.writeText(report.content || report.executive_summary || report.title);
      setCopyState("Report copied.");
    } catch {
      setCopyState("Copy failed.");
    } finally {
      setIsCopying(false);
    }
  }

  return (
    <AppShell>
      <div className="flex flex-col gap-6">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
          <div>
            <Button asChild variant="ghost" className="-ml-3 mb-2">
              <Link href={`/projects/${projectId}`}>
                <ArrowLeft className="size-4" />
                Project overview
              </Link>
            </Button>
            <h1 className="text-2xl font-semibold text-foreground">Final thesis health report</h1>
            <p className="mt-2 text-sm text-muted-foreground">
              {report?.title ?? "Review the generated report, scores, fixes, and defense preparation notes."}
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button asChild variant="outline">
              <Link href={`/projects/${projectId}/review`}>
                <Play className="size-4" />
                Run review again
              </Link>
            </Button>
            <Button onClick={() => void copyReport()} disabled={!report || isCopying}>
              <ClipboardCopy className="size-4" />
              Copy report
            </Button>
          </div>
        </div>

        {copyState ? (
          <div className={cn("rounded-md border p-3 text-sm", copyState.includes("failed") ? "border-danger/30 bg-danger/5 text-danger" : "border-success/30 bg-success/5 text-success")}>
            {copyState}
          </div>
        ) : null}

        {isLoading ? (
          <ReportState icon={<RefreshCw className="size-5 animate-spin" />} title="Loading report" description="Fetching the final thesis health report." />
        ) : error ? (
          <ReportState
            icon={<AlertCircle className="size-5" />}
            title="Report unavailable"
            description={error}
            action={
              <Button variant="outline" onClick={() => void loadReport()}>
                <RefreshCw className="size-4" />
                Retry
              </Button>
            }
          />
        ) : report ? (
          <>
            <section className="grid gap-4 lg:grid-cols-[280px_1fr]">
              <OverallScoreCard score={report.overall_score} createdAt={report.created_at} />
              <ScoreBreakdownCards scoreBreakdown={report.score_breakdown} />
            </section>

            <Card>
              <CardHeader>
                <CardTitle>Executive summary</CardTitle>
                <CardDescription>Top-level assessment generated by the report agent.</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="whitespace-pre-wrap text-sm leading-6 text-foreground">
                  {report.executive_summary || "No executive summary was included in this report."}
                </p>
              </CardContent>
            </Card>

            <section className="grid gap-4 xl:grid-cols-2">
              <PriorityFixList structuredReport={report.structured_report} />
              <DefenseQuestionsList structuredReport={report.structured_report} />
            </section>

            <Card>
              <CardHeader>
                <CardTitle>Markdown report</CardTitle>
                <CardDescription>Full generated report content.</CardDescription>
              </CardHeader>
              <CardContent>
                <pre className="max-h-[560px] overflow-auto whitespace-pre-wrap rounded-md border border-border bg-muted p-4 text-sm leading-6 text-foreground">
                  {report.content || "No markdown report content was included."}
                </pre>
              </CardContent>
            </Card>
          </>
        ) : null}
      </div>
    </AppShell>
  );
}

function ReportState({
  icon,
  title,
  description,
  action
}: {
  icon: ReactNode;
  title: string;
  description: string;
  action?: ReactNode;
}) {
  return (
    <Card>
      <CardContent className="flex flex-col items-center gap-4 py-12 text-center">
        <div className="flex size-10 items-center justify-center rounded-md bg-primary-soft text-primary">{icon}</div>
        <div>
          <h2 className="text-base font-semibold text-foreground">{title}</h2>
          <p className="mt-1 max-w-md text-sm text-muted-foreground">{description}</p>
        </div>
        {action}
      </CardContent>
    </Card>
  );
}
